### ISSUE TITLE
Place both language subtitles in the bottom

### ISSUE THREAD

**Issue by carlosvsilva** [peno64/repository.example#1]
Hi, is there any chance to be able to place the secondary language subtitle NOT on the top of the screen, but on the bottom near the main language subtitle? For language learning this would be important.

Maybe main sub in the bottom left, and secondary sub in the bottom right.
If longer subtitles overflow, then just place them together in the bottom, main lang above, and second lang under.

Is this possible to allow? Thanks

**Comment by peno64** [comment]
Please ask your question again here: https://github.com/peno64/service.subtitles.localsubtitle/issues
And remove it here (if you can)

**Comment by carlosvsilva** [comment]
done

**Comment by peno64** [comment]
see https://github.com/peno64/service.subtitles.localsubtitle/issues/14
